-- quiz_tables.sql
-- Please run this script in your Supabase SQL Editor to create the required table for Quiz Analytics

CREATE TABLE IF NOT EXISTS public.quiz_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    topic TEXT NOT NULL,
    score INTEGER NOT NULL DEFAULT 0,
    total_questions INTEGER NOT NULL DEFAULT 0,
    time_taken_seconds INTEGER NOT NULL DEFAULT 0,
    difficulty TEXT DEFAULT 'medium',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Note: Depending on your exact Supabase Role setup, you may need to enable RLS or adjust permissions. 
-- Since the Flask backend accesses Supabase, it will generally bypass RLS if using the service_role key.
